# Generated by Django 5.0 on 2023-12-21 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_veiculo_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente'),
        ),
    ]
