# Generated by Django 5.0 on 2023-12-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0002_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
