# Generated by Django 5.0 on 2023-12-21 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peca',
            old_name='quantidade',
            new_name='estoque',
        ),
    ]
