# Generated by Django 5.0 on 2023-12-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_rename_quantidade_peca_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peca',
            name='nome_peca',
            field=models.CharField(max_length=100),
        ),
    ]
