# Generated by Django 5.0 on 2023-12-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_alter_peca_nome_peca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_servico', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=254)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
