# Generated by Django 5.0 on 2023-12-22 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0003_alter_veiculo_cliente'),
        ('equipe', '0003_alter_funcionario_sobrenome'),
        ('servicos', '0004_servico'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(max_length=254)),
                ('data_inicio', models.DateField()),
                ('data_entrega', models.DateField(null=True)),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('equipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipe.equipe')),
                ('pecas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicos.peca')),
                ('servico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicos.servico')),
                ('veiculo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.veiculo')),
            ],
        ),
    ]
