# Generated by Django 5.0 on 2023-12-27 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemServico', '0001_initial'),
        ('servicos', '0004_servico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='pecas',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='servico',
        ),
        migrations.CreateModel(
            name='OrdemServicoPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(null=True)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordemServico.ordemservico')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.peca')),
            ],
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='pecas',
            field=models.ManyToManyField(blank=True, through='ordemServico.OrdemServicoPeca', to='servicos.peca'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='servico',
            field=models.ManyToManyField(null=True, to='servicos.servico'),
        ),
    ]
