# Generated by Django 5.0 on 2023-12-27 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemServico', '0003_remove_ordemservico_pecas_and_more'),
        ('servicos', '0004_servico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='pecas',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='servico',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='pecas',
            field=models.ManyToManyField(null=True, to='servicos.peca'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='servico',
            field=models.ManyToManyField(null=True, to='servicos.servico'),
        ),
    ]
